### ISSUE TITLE
Http 400/404

### ISSUE THREAD

**Issue by justinvdk** [caddy-dns/leaseweb#1]
When used in Caddy (replaced with `example.com`):

```
2021/05/18 20:31:45.494	ERROR	tls.obtain	will retry	{"error": "[subdoomain.example.com] Obtain: [subdoomain.example.com] solving challenges: presenting for challenge: adding temporary record for zone example.com.: Received StatusCode 400 from Leaseweb API (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/222222/1111111) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)", "attempt": 1, "retrying_in": 60, "elapsed": 3.5000000, "max_duration": 2500000}
```

and when trying to test (in a setup that used to work fine, libdns not caddy):

```
Received StatusCode 404 from Leaseweb API
```

Need to add a way to print the body anyway, as the API includes error information there.

**Comment by mholt** [comment]
A quick way to print the body (for dev/debugging, this is fine) is: `body, err := ioutil.ReadAll(resp.Body)`.

**Comment by justinvdk** [comment]
@mholt Thanks for that suggestion, that helped.

It has been a ride, I feel like I've bumped my head into literally any type of pitfall a newcomer could've bumped into.
From `go mod` outright telling me my versions don't exist to `go build` happily ignoring my own `GOPATH/src` :)

Furthermore, the bug was mainly that I made the wrong assumption (any assumption is wrong here) about the content of Name in the libdns.Record. Leaseweb expects the full domain name; so `sub.example.com`. Furthermore Leaseweb doesn't like the trailing dot that libdns (imho correctly) puts in the zone.

It is now at the point where a simple `xcaddy build --with github.com/caddy-dns/leaseweb` seems to do the trick with both subdomains and root domains. I haven't seen Caddy invoke SetRecords/GetRecords tho. I'm expecting the latter to maybe even return invalid data (Name with the zone suffixed).

Yes, I should've written tests, but I think that after this I'm happy I did not: I would've written my tests with the same (wrong!) assumptions. Is there any integration test that treats the Provider implementation as a black box? I think many more libdns providers would benefit from this, and would help finding these type of bugs earlier.

**Comment by mholt** [comment]
Ah... I see.

> From go mod outright telling me my versions don't exist to go build happily ignoring my own GOPATH/src :)

You probably know this by now, but Go no longer uses GOPATH.

> Leaseweb expects the full domain name; so sub.example.com

Different provider APIs have different requirements. libdns is designed to support both absolute names and relative names by separating the record names from the zone names. [From the godoc](https://pkg.go.dev/github.com/libdns/libdns):

> Records are described independently of any particular zone, a convention that grants Record structs portability across zones. As such, record names are partially qualified, i.e. relative to the zone. For example, an A record called "sub" in zone "example.com." represents a fully-qualified domain name (FQDN) of "sub.example.com.". Implementations should expect that input records conform to this standard, while also ensuring that output records do; adjustments to record names may need to be made before or after provider API calls, for example, to maintain consistency with all other libdns provider implementations. Helper functions are available in this package to convert between relative and absolute names.

`libdns.AbsoluteName()` and `libdns.RelativeName()` help with the conversion here: https://pkg.go.dev/github.com/libdns/libdns#AbsoluteName

> I would've written my tests with the same (wrong!) assumptions.

I agree, it's better to not write tests at all than to write wrong ones.

> Is there any integration test that treats the Provider implementation as a black box?

Not at this time, that I know of. Could be a good project.

**Comment by justinvdk** [comment]
> Ah... I see.
> 
> > From go mod outright telling me my versions don't exist to go build happily ignoring my own GOPATH/src :)
> 
> You probably know this by now, but Go no longer uses GOPATH.

Not really actually. But this does explain why some resources just assume one knows that `/usr/local/go` should/should be used.

> > Leaseweb expects the full domain name; so sub.example.com
> 
> Different provider APIs have different requirements. libdns is designed to support both absolute names and relative names by separating the record names from the zone names. [From the godoc](https://pkg.go.dev/github.com/libdns/libdns):
> 
> > Records are described independently of any particular zone, a convention that grants Record structs portability across zones. As such, record names are partially qualified, i.e. relative to the zone. For example, an A record called "sub" in zone "example.com." represents a fully-qualified domain name (FQDN) of "sub.example.com.". Implementations should expect that input records conform to this standard, while also ensuring that output records do; adjustments to record names may need to be made before or after provider API calls, for example, to maintain consistency with all other libdns provider implementations. Helper functions are available in this package to convert between relative and absolute names.
> 
> `libdns.AbsoluteName()` and `libdns.RelativeName()` help with the conversion here: https://pkg.go.dev/github.com/libdns/libdns#AbsoluteName

Yes, I think libdns does a good job at this, but I was so focussed on getting it to work that I overlooked helper methods such as this. Thanks for pointing them out! I've opened #2  for myself to clean this up a bit.

> > I would've written my tests with the same (wrong!) assumptions.
> 
> I agree, it's better to not write tests at all than to write wrong ones.
> 
> > Is there any integration test that treats the Provider implementation as a black box?
> 
> Not at this time, that I know of. Could be a good project.

Agreed. I'm still a noobie with go, such a thing would be a lot more efficient with some proper knowhow. I'll read through the libdns docs more carefully first and play with some testing in go in general.

Closing this issue, as it is resolved. Thanks @mholt  for the responsiveness, I couldn't wish for a more helpful start with a new language 🎊 💪🏻
