### ISSUE TITLE
Leaseweb api always returns 400, but not when using libdns example

### ISSUE THREAD

**Issue by pimlie** [caddy-dns/leaseweb#3]
What's the best way to debug when the leaseweb api returns a [400 bad request](https://github.com/LeaseWeb/api-standards?tab=readme-ov-file#http-status-codes) error? Would it be possible to return/log the error details that Leaseweb returns in the response body?

When I compile the https://github.com/libdns/leaseweb example code with my api key the request are done succesfully, but when using through caddy with `tls  { dns leaseweb API_KEY }` it seems all requests fail with a 400.:

```
ERR ts=1 logger=tls.obtain msg=will retry error=[*.mydomain.com] Obtain: [*.mydomain.com] solving challenges: presenting for challenge: adding temporary record for zone "mydomain.com.": Received StatusCode 400 from Leaseweb API. (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/x/y) (ca=https://acme-staging-v02.api.letsencrypt.org/directory) attempt=3 retrying_in=120 elapsed=186 max_duration=259200
```

To be clear, the tls request is for a wildcard domain hence the *.mydomain.com

**Comment by justinvdk** [comment]
Hey, sorry I missed this issue. I'm not actively using caddy+leaseweb anymore, and there never was a lot of interest. Never had to do actual maintaining.

This also was my only real golang stint, but the approach you came up with was very similar to mine if I recall correctly.
Thanks for documenting, I will put it in the README.md if you're okay with that.

**Comment by justinvdk** [comment]
Awesome.
Seem like `xcaddy build --with github.com/caddy-dns/leaseweb && ./caddy run` is now working with leaseweb configured as provider:

```caddyfile
some-domain.example.org:8443 {
	tls {
		dns leaseweb "<api-key>"
	}
	respond "Hello, world!"
}

```

**Comment by pimlie** [comment]
Awesome, many thanks!
